runtime: python311

entrypoint: python main.py

instance_class: F2

env_variables:
  MONGO_URI: "mongodb+srv://admin:admin@cluster0.moiqqfd.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 2
